apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-svc
  namespace: microservices
  labels:
    app: ${APP_NAME}
spec:
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: ${SERVICE_PORT}
      targetPort: ${TARGET_PORT}
  type: ClusterIP 
