apiVersion: v1
kind: Service
metadata:
  name: {VARIABLE}-svc
  namespace: microservices
  labels:
    app: {VARIABLE}
spec:
  selector:
    app: {VARIABLE}
  ports:
    - protocol: TCP
      port: {VARIABLE}
      targetPort: {VARIABLE}
  type: ClusterIP 