name: trivy filesystem scan
on:
  ["push", "workflow_dispatch"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in filesystem mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scanners: 'vuln,config,secret'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-filesystem-scan.table'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-filesystem-scan
          path: 'trivy-filesystem-scan.table'
